// Generated by CoffeeScript 2.2.3
(function() {
  var _configuraciones, _resources, app, indexController;

  app = angular.module("appExemplo", ['ngResource']);

  _configuraciones = function() {
    return {
      urlApi: "http://104.131.187.65:1880"
    };
  };

  _resources = function(configuraciones, $resource) {
    return $resource("", {}, {
      elementos: {
        url: configuraciones.urlApi + "/elementos",
        method: 'GET',
        isArray: false
      },
      afp: {
        url: configuraciones.urlApi + "/afp",
        method: 'GET',
        isArray: false
      }
    });
  };

  indexController = function($scope, recursos) {
    // obtengo desde el recurso, el listado de elementos
    console.log("mensaje por consola");
    $scope.sinUniverso = false;
    $scope.sinBuscados = false;
    return recursos.elementos(function(el) {
      $scope.elementos = el;
      if (el.universo.length === 0) {
        $scope.sinUniverso = true;
      }
      if (el.buscados.length === 0) {
        return $scope.sinBuscados = true;
      }
    });
  };

  app.factory("configuraciones", [_configuraciones]);

  app.factory("recursos", ["configuraciones", "$resource", _resources]);

  app.controller("indexController", ["$scope", "recursos", indexController]);

}).call(this);
