// Generated by CoffeeScript 2.2.3
(function() {
  var _configuraciones, _directivaListadoAFP, _directivaSelectorAFP, _resources, app, indexController;

  app = angular.module("appExemplo", ['ngResource']);

  _configuraciones = function() {
    return {
      urlApi: "http://104.131.187.65:1880"
    };
  };

  _directivaListadoAFP = function($http, configuraciones) {
    return {
      restrict: 'E',
      scope: {},
      template: "<ul> <li ng-repeat=' afp in afps'> {{afp}}</li> </ul>",
      link: function($scope) {
        return $http.get(configuraciones.urlApi + "/afp").then(function(resp) {
          return $scope.afps = resp.data;
        });
      }
    };
  };

  _directivaSelectorAFP = function(recursos) {
    return {
      restrict: 'E',
      scope: {},
      templateUrl: "templates/directive.selector.afp.html",
      link: function($scope) {
        return recursos.afp(function(resp) {
          return $scope.afps = resp;
        });
      }
    };
  };

  _resources = function(configuraciones, $resource) {
    return $resource("", {}, {
      elementos: {
        url: configuraciones.urlApi + "/elementos",
        method: 'GET',
        isArray: false
      },
      afp: {
        url: configuraciones.urlApi + "/afp",
        method: 'GET',
        isArray: true
      }
    });
  };

  indexController = function($scope, recursos) {
    console.log("mensaje por consola");
    $scope.sinUniverso = false;
    $scope.sinBuscados = false;
    // obtengo desde el recurso, el listado de elementos
    return recursos.elementos(function(el) {
      $scope.elementos = el;
      if (el.universo.length === 0) {
        $scope.sinUniverso = true;
      }
      if (el.buscados.length === 0) {
        return $scope.sinBuscados = true;
      }
    });
  };

  app.factory("configuraciones", [_configuraciones]);

  app.factory("recursos", ["configuraciones", "$resource", _resources]);

  app.directive('listadoAfp', ["$http", "configuraciones", _directivaListadoAFP]);

  app.directive('selectorAfp', ["recursos", _directivaSelectorAFP]);

  app.controller("indexController", ["$scope", "recursos", indexController]);

}).call(this);
