// Generated by CoffeeScript 2.2.3
(function() {
  var _configuraciones;

  this.app = angular.module("appExemplo", ['ngResource']);

  _configuraciones = function() {
    return {
      urlApi: "http://104.131.187.65:1880",
      urlRest: "https://jsonplaceholder.typicode.com"
    };
  };

  app.factory("configuraciones", [_configuraciones]);

}).call(this);
