// Generated by CoffeeScript 2.2.3
(function() {
  var _directivaListadoAFP, _directivaSelectorAFP;

  _directivaListadoAFP = function($http, configuraciones) {
    return {
      restrict: 'E',
      scope: {},
      template: "<ul> <li ng-repeat=' afp in afps'> {{afp}}</li> </ul>",
      link: function($scope) {
        return $http.get(configuraciones.urlApi + "/afp").then(function(resp) {
          return $scope.afps = resp.data;
        });
      }
    };
  };

  _directivaSelectorAFP = function(recursos) {
    return {
      restrict: 'E',
      scope: {},
      templateUrl: "templates/directive.selector.afp.html",
      link: function($scope) {
        return recursos.afp(function(resp) {
          return $scope.afps = resp;
        });
      }
    };
  };

  app.directive('listadoAfp', ["$http", "configuraciones", _directivaListadoAFP]);

  app.directive('selectorAfp', ["recursos", _directivaSelectorAFP]);

}).call(this);
