// Generated by CoffeeScript 2.2.3
(function() {
  var _resources, _resourcesREST;

  _resources = function(configuraciones, $resource) {
    return $resource("", {}, {
      elementos: {
        url: configuraciones.urlApi + "/elementos",
        method: 'GET',
        isArray: false
      },
      afp: {
        url: configuraciones.urlApi + "/afp",
        method: 'GET',
        isArray: true
      }
    });
  };

  _resourcesREST = function(configuraciones, $resource) {
    return $resource(configuraciones.urlRest + "/users/:id", {});
  };

  app.factory("recursos", ["configuraciones", "$resource", _resources]);

  app.factory("recursosjsonplaceholder", ["configuraciones", "$resource", _resourcesREST]);

}).call(this);
